package neton.client.Utils;

public class ResponseCode {
    public static final int CODE_1XX_CONTINUE = 100;
    public static final int CODE_1XX_Switching_Protocols = 101;
    public static final int CODE_2XX_ACCEPTED = 202;
    public static final int CODE_2XX_CREATED = 201;
    public static final int CODE_2XX_NON_AUTHORITATIVE_INFORMATION = 203;
    public static final int CODE_2XX_NO_CONTENT = 204;
    public static final int CODE_2XX_PARTIAL_CONTENT = 206;
    public static final int CODE_2XX_RESET_CONTENT = 205;
    public static final int CODE_2XX_SUCCESS = 200;
    public static final int CODE_3XX_FOUND = 302;
    public static final int CODE_3XX_MOVED_PERMANENTLY = 301;
    public static final int CODE_3XX_MULTIPLE_CHOICES = 300;
    public static final int CODE_3XX_NOT_MODIFIED = 304;
    public static final int CODE_3XX_SEE_OTHER = 303;
    public static final int CODE_3XX_TEMPORARY_REDIRECT = 307;
    public static final int CODE_3XX_USE_PROXY = 305;
    public static final int CODE_4XX_BAD_REQUEST = 400;
    public static final int CODE_4XX_CONFLICT = 409;
    public static final int CODE_4XX_EXPECTATION_FAILED = 417;
    public static final int CODE_4XX_FORBIDDEN = 403;
    public static final int CODE_4XX_GONE = 410;
    public static final int CODE_4XX_LENGTH_REQUIRED = 411;
    public static final int CODE_4XX_METHOD_NOT_ALLOWED = 405;
    public static final int CODE_4XX_NOT_ACCEPTABLE = 406;
    public static final int CODE_4XX_NOT_FOUND = 404;
    public static final int CODE_4XX_PAYMENT_REQUIRED = 402;
    public static final int CODE_4XX_PRECONDITION_FAILED = 412;
    public static final int CODE_4XX_PROXY_AUTHENTICATION_REQUIRED = 407;
    public static final int CODE_4XX_REQUESTED_RANGE_NOT_SATISFIABLE = 416;
    public static final int CODE_4XX_REQUEST_ENTITY_TOO_LARGE = 413;
    public static final int CODE_4XX_REQUEST_TIMEOUT = 408;
    public static final int CODE_4XX_REQUEST_URI_TOO_LARGE = 414;
    public static final int CODE_4XX_UNAUTHORIZED = 401;
    public static final int CODE_4XX_UNSUPPORTED_MEDIA_TYPE = 415;
    public static final int CODE_5XX_BAD_GATEWAY = 502;
    public static final int CODE_5XX_GATEWAY_TIMEOUT = 504;
    public static final int CODE_5XX_HTTP_VERSION_NOT_SUPPORTED = 505;
    public static final int CODE_5XX_INTERNAL_SERVER_ERROR = 500;
    public static final int CODE_5XX_NOT_IMPLEMENTED = 501;
    public static final int CODE_5XX_SERVICE_UNAVAILABLE = 503;
    public static final int CODE_6XX_CONNECT_ERROR = 600;
    public static final int CODE_6XX_DNS_ERROR = 601;
    public static final int CODE_DEFAULT = 0;
}
